export interface getDocumentInfo {
  id: string;
  title: string;
  address: string;
  photos: string[] | null;
  rate: string | null;
  discounted_price: string | null;
  price: string;
  tags: string[];
  last_updated: string;
  capacity: number;
  location: { lat: string; lng: string };
  categories: { name: string };
  bathrooms: number;
  parking: number;
  rooms: number;
  yard_type: string;
  num_comments: number;
  discount_id: string | null;
  transaction_type: string;
  sellerId: string;
  sellerName: string;
  caption: string;
  favoriteId: string | null;
  bookings: number;
  isFavorite: boolean;
  users: {
    id: string;
    role: string;
    membershipDate: string | null;
    email: string;
    phoneNumber: string;
    emailVerified: boolean;
    verificationCode: string;
    verificationCodeExpires: string;
    resetCode: string | null;
    resetCodeExpires: string | null;
    fullName: string;
    firstName: string;
    lastName: string;
    profilePicture: string;
    createdAt: string;
    updatedAt: string;
    additionalPercentage: number;
  };
}